/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import { useState, useEffect } from "react";
import HeroSectionData from "../data/getir/Hero.json";
import Herosection from "./components/Herosection";
import Navbar from "./components/Navbar";
import Categories from "./components/Categories";
import Campaigns from "./components/Campaigns";
import Application from "./components/Application";
import { MainContext } from "./Context";
import GetirCategoryData from "../data/getir/Categories.json";
import GetirCampaginsData from "../data/getir/Campagins.json";
import WrapperData from "../data/getir/HeroWrapper.json"
import GetirCardData from "../data/getir/Card.json";
import Cards from "./components/Cards";
import Footer from "./components/Footer";
import Subfooter from "./components/Subfooter";

export default function Home() {
  const [heroData, setHeroData] = useState(HeroSectionData);
  const [categories, setCategories] = useState(GetirCategoryData);
  const [campagins, setCampagins] = useState(GetirCampaginsData);
  const [card, setCard] = useState(GetirCardData);
  const [categoryComponent, setCategoryComponent] = useState(<Categories />);
  const [campaginsComponent, setcampaginsComponent] = useState(<Campaigns />);
  const [questions, setQuestions] = useState();
  const [getirYemekComponent, setgetirYemekComponent] = useState();
  const [heroWrapperData, setHeroWrapperData] = useState(WrapperData);

  const data = {
    categories,
    setCategories,
    campagins,
    setCampagins,
    card,
    setCard,
    categoryComponent,
    setCategoryComponent,
    campaginsComponent,
    setcampaginsComponent,
    getirYemekComponent,
    setgetirYemekComponent,
    questions,
    setQuestions,
    heroData,
    setHeroData,
    heroWrapperData,
    setHeroWrapperData,
  };
  return (
    <MainContext.Provider value={data}>
      <Head>
        <title>Getir - Dakikalar İçinde Kapınızda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <Herosection />
      {categoryComponent}
      {campaginsComponent}
      {getirYemekComponent}
      <Application />
      <Cards />
      {questions}
      <Footer />
      <Subfooter />
    </MainContext.Provider>
  );
}
